
export const TRIPS_LOAD_START = 'TRIPS_LOAD_START';
export const TRIPS_LOAD_SUCESS = 'TRIPS_LOAD_SUCESS';
export const TRIPS_LOAD_FAILED = 'TRIPS_LOAD_FAILED';

export const TRIP_DETAILS_LOAD_START = 'TRIP_DETAILS_LOAD_START';
export const TRIP_DETAILS_LOAD_SUCCESS = 'TRIP_DETAILS_LOAD_SUCCESS';
export const TRIP_DETAILS_LOAD_FAILED = 'TRIP_DETAILS_LOAD_FAILED';
